// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDUK9fw1qKVPuhIxV3Glt0-qgy59jGJVs',
    appId: '1:738578900785:web:8bd23320b23756db9af210',
    messagingSenderId: '738578900785',
    projectId: 'fasum-app-4651e',
    authDomain: 'fasum-app-4651e.firebaseapp.com',
    storageBucket: 'fasum-app-4651e.firebasestorage.app',
    measurementId: 'G-F9S95F5BBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZ3b3mNxQQ-7R0MSo8fLf_LCxdh_V2fA',
    appId: '1:738578900785:android:bf3aecd9dd6c0eae9af210',
    messagingSenderId: '738578900785',
    projectId: 'fasum-app-4651e',
    storageBucket: 'fasum-app-4651e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm2Q8nBixB6Bwa8HoNmAJj_s8g92rwo9U',
    appId: '1:738578900785:ios:7f3753e0760fe1d09af210',
    messagingSenderId: '738578900785',
    projectId: 'fasum-app-4651e',
    storageBucket: 'fasum-app-4651e.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm2Q8nBixB6Bwa8HoNmAJj_s8g92rwo9U',
    appId: '1:738578900785:ios:7f3753e0760fe1d09af210',
    messagingSenderId: '738578900785',
    projectId: 'fasum-app-4651e',
    storageBucket: 'fasum-app-4651e.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDUK9fw1qKVPuhIxV3Glt0-qgy59jGJVs',
    appId: '1:738578900785:web:cbf26c3504af44599af210',
    messagingSenderId: '738578900785',
    projectId: 'fasum-app-4651e',
    authDomain: 'fasum-app-4651e.firebaseapp.com',
    storageBucket: 'fasum-app-4651e.firebasestorage.app',
    measurementId: 'G-3PEKXDZFLR',
  );
}
