// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhR3etsCGMK8hQYby6Op1Hp3DL6Q9J04U',
    appId: '1:324281304039:web:a86eb37de8051948d77342',
    messagingSenderId: '324281304039',
    projectId: 'frida-app-20af9',
    authDomain: 'frida-app-20af9.firebaseapp.com',
    databaseURL: 'https://frida-app-20af9-default-rtdb.firebaseio.com',
    storageBucket: 'frida-app-20af9.firebasestorage.app',
    measurementId: 'G-260MP205MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR5HyX1CWPsRNzoKcFaakEIFYqs2pBMpU',
    appId: '1:324281304039:android:6e911c8bbd3b1cf2d77342',
    messagingSenderId: '324281304039',
    projectId: 'frida-app-20af9',
    databaseURL: 'https://frida-app-20af9-default-rtdb.firebaseio.com',
    storageBucket: 'frida-app-20af9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF_ORdTpfyrpePS0_4GU2h8woru1wJ7TI',
    appId: '1:324281304039:ios:d2749d748f2160d8d77342',
    messagingSenderId: '324281304039',
    projectId: 'frida-app-20af9',
    databaseURL: 'https://frida-app-20af9-default-rtdb.firebaseio.com',
    storageBucket: 'frida-app-20af9.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF_ORdTpfyrpePS0_4GU2h8woru1wJ7TI',
    appId: '1:324281304039:ios:d2749d748f2160d8d77342',
    messagingSenderId: '324281304039',
    projectId: 'frida-app-20af9',
    databaseURL: 'https://frida-app-20af9-default-rtdb.firebaseio.com',
    storageBucket: 'frida-app-20af9.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhR3etsCGMK8hQYby6Op1Hp3DL6Q9J04U',
    appId: '1:324281304039:web:d63a4577a206210fd77342',
    messagingSenderId: '324281304039',
    projectId: 'frida-app-20af9',
    authDomain: 'frida-app-20af9.firebaseapp.com',
    databaseURL: 'https://frida-app-20af9-default-rtdb.firebaseio.com',
    storageBucket: 'frida-app-20af9.firebasestorage.app',
    measurementId: 'G-BGPBV18NXE',
  );

}